apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: fastapi-app-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  tls:
  - hosts:
      - fastapi-app.127.0.0.1.nip.io
    secretName: https-certs

  rules:
  - host: fastapi-app.127.0.0.1.nip.io

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi-app-service
            port:
              number: 80
