# -*- mode: Python -*

k8s_yaml('kubernetes.yaml')

k8s_resource('flask-app', port_forwards=8000)

docker_build(
    'flask-app-image',
    '.',
    # dockerfile="Dockerfile",
    build_args={'flask_debug': 'True'},
    live_update=[
        sync('.', '/app'),
])

local_resource(
  "restart-flask-app",
  cmd="kubectl rollout restart deploy/flask-app",
  deps=["."],  # watch folders to restart the deployment when files change
  auto_init=False
)