apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb_username: username
  mongodb_password: password
  mongodb_node_0_url: mongodb://mongodb-0.mongodb-headless:27017
  mongodb_node_1_url: mongodb://mongodb-1.mongodb-headless:27017
  mongodb_node_2_url: mongodb://mongodb-2.mongodb-headless:27017
  mongodb_nodes_url: mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017,mongodb-2.mongodb-headless:27017
  mongodb_cluster_uri: mongodb://username:password@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017,mongodb-2.mongodb-headless:27017/?replicaSet=rs0&authSource=admin
