#
# Flask APP
#

def example_co_flask():
    COMPANY_FOLDER = './companies/example_co'
    APP_FOLDER = f'{COMPANY_FOLDER}/flask/app'
    K8S_FOLDER = f'{COMPANY_FOLDER}/flask/infra/k8s/manifests/'

    # docker build
    docker_build(
        'flask-app-image',
        APP_FOLDER,
        build_args={'flask_debug': 'True'},
        live_update=[
            sync(APP_FOLDER, '/app'),
            run('sh -lc "kill -HUP 1"'),
        ]
    )

    # kubernetes manifests
    k8s_yaml(f'{K8S_FOLDER}/1.deployment.yaml')
    k8s_yaml(f'{K8S_FOLDER}/2.service.yaml')
    k8s_yaml(f'{K8S_FOLDER}/3.ingres.yaml')

    # kubernetes ingress
    k8s_resource(
        'flask-app',
        objects=['flask-app-ingress:ingress'],
        links=['http://flask-app.127.0.0.1.nip.io/'],
        labels=['flask-app']
    )
